title: Scott's Docs
description: Sample documentation site
remote_theme: just-the-docs/just-the-docs

url: https://docs.scottjack.me/

aux_links:
  "scottjack.me":
    - "//scottjack.me/"

aux_links_new_tab: true